# Beginner tag groups: tag -> slugs. A keyword can appear in many groups.
# Written in the language a beginner would actually type or tap.
GROUPS = {
"cute": ["kawaii-gamer","dual-kawaii","pixiecore","neko","yume-kawaii","pixel-cutie","gothic-kawaii","bubble-goth","soft-macabre","pop-kei","party-kei","toyism","pasta-art","childs-drawing","furry-art","doodle","cartoon","faux-naif-art","naive","claymation"],
"spooky": ["emo","neo-gothic","cybergoth","anglo-gothic","gothic-americana","soft-macabre","biomechanical-art","hyperspace-noir","angura-kei","abject-art","whimsigoth","ominous","pareidolia","gothic-kawaii","dark-colors"],
"dark colors": ["emo","grunge","cybergoth","neo-gothic","anglo-gothic","gothic-americana","biomechanical-art","hyperspace-noir","low-key-lighting","noir-grade","bleach-bypass","trash-polka","chiaroscuro","ominous","angura-kei"],
"pastel colors": ["pastel-palette","pastel-academia","pink-parisian","lilac-femme","rococo","neo-rococo","yume-kawaii","pixiecore","watercolor","soft-grunge","dual-kawaii","party-kei","bubble-goth","biomorphic-art","watercolor-ornamental","suminagashi","toile"],
"vibrant colors": ["fauvism","acid-art","acidwave","pop-kei","city-pop","memphis-group","technicolor","orphism","synchromism","chiptune","jewel-tones","neon-glow","graffiti-pop-art","algorave","toyism","surrealist-pop","iridescent","stained-glass","harlem-renaissance","new-romantic","funk-art"],
"pink": ["pink-parisian","pixiecore","yume-kawaii","gothic-kawaii","party-kei","pastel-palette","bubble-goth","lilac-femme","neon-noir"],
"purple": ["lilac-femme","whimsigoth","neon-glow","acidwave"],
"gold": ["opulent","rinpa","iconography","baroque","barococo","rococo","night-luxe","golden-hour","golden-autumn","golden-hour-grade","luminism","art-deco-era","kishangarh-painting"],
"black and white": ["noir-grade","rayograms","line-drawing","charcoal-sketch","ascii-art","graffito","chiaroscuro"],
"neutral colors": ["muted-palette","wabi-sabi","chic-modernist","tonalist","mori-kei","karesansui","concrete-art","preppy","organic-abstraction","weathered"],
"golden light": ["golden-hour","golden-hour-grade","golden-autumn","luminism","candlelight","rim-light","lens-flare","tonalist"],
"soft light": ["soft-key","high-key-lighting","overcast-light","tonalist","luminism","fog","ethereal","dreamscape","pastel-academia","digital-impressionism","atmospheric-landscape-painting"],
"dramatic light": ["chiaroscuro","low-key-lighting","hard-light","rim-lighting","baroque","volumetric-light","silhouette","noir-grade","dutch-angle"],
"neon light": ["neon-glow","cybergoth","city-pop","neon-noir","cyberpunk","cybernetic-punk","acidwave","algorave","bubble-goth","night-luxe","hyperspace-noir","practical-lighting","cyber-fairy-grunge","cybergrunge"],
"night": ["night-luxe","neon-noir","noir-grade","day-for-night","hyperspace-noir","city-pop","bokeh","low-key-lighting","candlelight"],
"glow": ["bioluminescence","neon-glow","iridescent","volumetric-light","luminism","encaustic-art","lens-flare","ethereal"],
"dreamy": ["dreamscape","ethereal","yume-kawaii","retro-fairycore","pixiecore","fairy-academia","abstract-romanticism","phantastische-kunst","lyrical-abstraction","cross-dissolve","fog","surrealist-pop","decalcomania","pareidolia","suminagashi","lilac-femme"],
"magical": ["fairy-grunge","fairy-academia","retro-fairycore","pixiecore","whimsigoth","mythological","phantastische-kunst","cyber-fairy-grunge","ethereal","dreamscape","stained-glass"],
"cozy": ["country","mori-kei","candlelight","romantic-academia","pastel-academia","whimsigoth","analog","folk-art","naive","first-snow","golden-autumn"],
"elegant": ["high-fashion","editorial","chic-modernist","night-luxe","art-deco-era","luminism","rinpa","toile","kishangarh-painting","kangra-painting","mannerism","afrovictorian","victorian-era","opulent","line-drawing","anamorphic"],
"playful": ["toyism","memphis-group","pasta-art","funk-art","doodle","cartoon","caricature","pop-kei","party-kei","pixel-cutie","chiptune","childs-drawing","graffiti-pop-art","bubble-bujo","3d-pavement-art","whip-pan","smash-cut"],
"romantic": ["romantic-academia","pink-parisian","kangra-painting","rococo","golden-hour","golden-hour-grade","bokeh","cross-dissolve","toile","victorian-era","new-romantic"],
"moody": ["tonalist","fog","grunge","soft-grunge","gothic-americana","noir-grade","bleach-bypass","low-key-lighting","overcast-light","monsoon-rain","anglo-gothic","atmospheric-landscape-painting","ominous"],
"calm": ["wabi-sabi","karesansui","serene","suminagashi","tonalist","luminism","mori-kei","organic-abstraction","land-art","seascape","cloudscape","static-hold"],
"edgy": ["trash-polka","grunge","cybergrunge","cybernetic-punk","punk","alternative","emo","acid-art","biomechanical-art","graffito","smash-cut","dutch-angle","bleach-bypass"],
"retro": ["retro-70s","city-pop","analog","new-romantic","memphis-group","chiptune","y2k","technicolor","16mm-film-look","film-photography","retro-fairycore","acidwave","pixel-cutie","harlem-renaissance","preppy"],
"vintage": ["victorian-era","art-deco-era","antique-grunge","rococo-revival","dolly-kei","toile","luminism","tonalist","rayograms","afrovictorian","weathered","film-photography","baroque","mannerism","rococo"],
"futuristic": ["abstract-futuristic","abstract-tech","cybernetic-punk","augmented-reality-art","hyperspace-noir","binary-art","algorithmic-art","low-poly-art","artificial-nature","biomechanical-art","cyberculture","brushed-metal"],
"nature": ["mori-kei","botanical-art","naturaleza","eco-art","land-art","moss-covered","fairy-grunge","organic-abstraction","biomorphic-art","karesansui","atmospheric-landscape-painting","golden-autumn","first-snow","seascape","cloudscape","microscape","monsoon-rain","brutalist-botanical"],
"urban": ["cityscape","graffiti-pop-art","graffito","city-pop","neon-noir","cyberculture","3d-pavement-art","expressionist-architecture","hyperspace-noir"],
"japanese style": ["dolly-kei","angura-kei","mori-kei","pop-kei","yume-kawaii","neko","rinpa","suminagashi","karesansui","wabi-sabi","ukiyo-e-vaporwave","city-pop","party-kei"],
"world cultures": ["gond-painting","haida-art","hopi-art","kangra-painting","kishangarh-painting","afrovictorian","harlem-renaissance","folk-art","rinpa","suminagashi"],
"painting": ["oil-painting","watercolor","fauvism","baroque","rococo","mannerism","luminism","tonalist","digital-impressionism","figurative-expressionism","lyrical-abstraction","encaustic-art","botanical-art","atmospheric-landscape-painting","gond-painting","kangra-painting","kishangarh-painting","naive","faux-naif-art","photorealism","synchromism","orphism","vorticism","abstract-romanticism","hard-edge-painting","decalcomania","phantastische-kunst"],
"drawing": ["line-drawing","charcoal-sketch","doodle","rough-sketch-line-drawing","comic-art","caricature","childs-drawing","illustration","cartoon","toile","bubble-bujo"],
"photography": ["film-photography","candid","editorial","macro-photography","long-exposure","rayograms","photorealism","analog","high-fashion"],
"pattern": ["toile","watercolor-ornamental","gond-painting","memphis-group","suminagashi","typographic-art","iconography","rinpa"],
"craft": ["papercraft","claymation","assemblage","found-object-art","salvage-art","mixed-media","encaustic-art","pasta-art","tactile-art","folk-art","stained-glass"],
"abstract": ["synchromism","orphism","vorticism","lyrical-abstraction","abstract-romanticism","organic-abstraction","biomorphic-art","concrete-art","hard-edge-painting","algorithmic-art","zombie-formalism","visual-music","abstract-futuristic","abstract-tech","suminagashi","decalcomania","magnetic-art"],
"fashion": ["high-fashion","dolly-kei","mori-kei","pop-kei","party-kei","angura-kei","preppy","new-romantic","alternative","emo","cybergoth","soft-grunge","afrovictorian","night-luxe","editorial","y2k","lilac-femme"],
"weird and wonderful": ["surrealist-pop","avant-pop-surrealism","pareidolia","object-oriented-ontology","neo-dada","abject-art","funk-art","artificial-nature","anamorphic-art","decalcomania","zombie-formalism","ontology","post-conceptualism","derivative-art","post-modernism"],
"tech": ["binary-art","ascii-art","abstract-tech","algorithmic-art","augmented-reality-art","digital-animation","cyberculture","algorave","chiptune","pixel-cutie","low-poly-art","kinetic-art","magnetic-art","visual-music"],
"texture": ["weathered","cracked-porcelain","velvet","brushed-metal","moss-covered","encaustic-art","tactile-art","palimpsest-art","graffito","iridescent","heat-haze","mixed-media"],
"architecture": ["expressionist-architecture","brutalist-botanical","neo-gothic","cityscape","karesansui"],
"words and letters": ["typographic-art","found-text-art","bubble-bujo","ascii-art","palimpsest-art"],
# video / cinematography beginner tags
"camera movement": ["dolly-in","dolly-out","tracking-shot","crane-shot","handheld","steadicam","whip-pan","dolly-zoom","orbit","push-in","tilt-up","aerial-shot","static-hold","long-take"],
"framing": ["extreme-wide-shot","wide-shot","medium-shot","close-up","extreme-close-up","over-the-shoulder","low-angle","high-angle","dutch-angle","pov-shot","establishing-shot"],
"lens effect": ["anamorphic","shallow-depth-of-field","deep-focus","rack-focus","wide-angle-lens","telephoto-compression","lens-flare","bokeh"],
"lighting": ["rim-lighting","rim-light","low-key-lighting","high-key-lighting","practical-lighting","motivated-lighting","hard-light","soft-key","silhouette","volumetric-light","candlelight","chiaroscuro"],
"editing": ["match-cut","smash-cut","cross-dissolve","j-cut","l-cut","slow-motion","speed-ramp"],
"film look": ["teal-and-orange","bleach-bypass","day-for-night","golden-hour-grade","16mm-film-look","technicolor","noir-grade","neon-noir","film-photography","analog"],
"slow and emotional": ["slow-motion","dolly-in","push-in","close-up","cross-dissolve","golden-hour-grade","soft-key"],
"fast and exciting": ["speed-ramp","whip-pan","smash-cut","handheld","tracking-shot","teal-and-orange","orbit"],
"beginner favorite": ["golden-hour","watercolor","pastel-palette","close-up","wide-shot","soft-key","golden-hour-grade","bokeh","slow-motion","cartoon","line-drawing","botanical-art","cozy"],
}
